<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    // const promise=new Promise(function(resolve,reject){
    //     // Do an async task
    //     // Database calls , cryptography , network calls
    //     setTimeout(function(){
    //         console.log('Async task is complete');
    //         resolve()
    //     },1000)
    // })
    // // then is directly related to resolve
    // promise.then(function(){
    //     console.log("Promise completed");
    // })

    // new Promise(function(resolve,reject){
    //     setTimeout(function(){
    //         console.log("Async task 2")
    //         resolve()
    //     },1000);
    // }).then(function(){
    //     console.log("promise 2 completed")
    // })

    // const promiseThree=new Promise(function(resolve,reject){
    //     setTimeout(function(){
    //         resolve({name:"Mehul",Age:21});
    //         console.log("Hello i am 3rd task");
    //     },3000)
    // })
    // promiseThree.then(function(user){
    //     console.log(user);
    // })

    // const promiseFour=new Promise(function(resolve,reject){
    //     let error=true;
    //     if(!error){
    //         resolve({email:"mehul2409@gmail.com",password:"mehul24."})
    //     }
    //     else{
    //         reject('Error : encountered')
    //     }
    // })
    // // promiseFour.then((user)=>{
    // //     console.log(user.username);
    // // }).catch()
    // promiseFour.then((user)=>{
    //     console.log(user.email);
    //     return user.password;
    // }).then((important)=>{
    //     //important has password of user
    //     console.log(important);
    //     console.log(password);
    // }).catch((str)=>{
    //     console.log(str);
    // }).finally(()=>{console.log("The promise is either resolved or rejected");})
    // // this is chaining , means value from 1st then is shared to second then


    const promiseFive=new Promise(function(resolve,reject){
        setTimeout(()=>{
            let error=true;
            if(error){
                resolve({username:"Javascript",password:"mehul"})
            }
            else{
                reject('ERROR : JS went wrong')
            }
        },1000)
    })
    async function consumePromiseFive(){
        try{
            const response=await promiseFive
            console.log(response)
        }
        catch(error){
            console.log(error);
        }
    }
    // fetch('https://api.github.com/users/hiteshchoudhary').then((response) => {
    //     return response.json()
    // }).then((data) => {
    //         console.log(data);
    // }).catch((error) => console.log(error))

</script>
</html>